# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-11 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20190110_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='join_date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 11, 9, 25, 49, 292262, tzinfo=utc)),
        ),
    ]
