# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-07 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_auto_20190107_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2019, 1, 7, 8, 36, 9, 681099, tzinfo=utc)),
        ),
    ]
