# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-16 08:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0019_auto_20190116_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2019, 1, 16, 8, 10, 47, 917416, tzinfo=utc)),
        ),
    ]
