# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-07 09:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20190107_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='email',
            field=models.EmailField(default=0, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='lab',
            name='join_date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 7, 9, 14, 32, 130631, tzinfo=utc)),
        ),
    ]
