# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-17 01:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0024_auto_20190116_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='join_date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 17, 1, 41, 33, 481743, tzinfo=utc)),
        ),
    ]
