# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-01 10:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0001_initial'),
        ('doctor', '0001_initial'),
        ('staff', '0001_initial'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_list', models.TextField(default='0')),
                ('comment', models.TextField(default='0')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='D_Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.TextField(default='0')),
                ('comment', models.TextField(default='0')),
                ('follow_on_date', models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 1, 10, 2, 47, 41218, tzinfo=utc))),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.TextField(default='0')),
                ('test_date', models.DateField(verbose_name=datetime.datetime(2019, 1, 1, 10, 2, 47, 41218, tzinfo=utc))),
                ('amount', models.IntegerField(default='0')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medical')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='saud', max_length=50)),
                ('email', models.EmailField(default='saud@gmail.com', max_length=150)),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=2)),
                ('age', models.IntegerField(default=0)),
                ('date', models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 1, 10, 2, 47, 41218, tzinfo=utc))),
                ('address', models.CharField(default='0', max_length=30)),
                ('phoneno', models.IntegerField(default=0)),
                ('about', models.TextField(default='0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Test_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(default='0', max_length=200)),
                ('test_type', models.CharField(default='0', max_length=100)),
                ('test_date', models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2019, 1, 1, 10, 2, 47, 41218, tzinfo=utc))),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient_Profile.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient_Profile.Patient'),
        ),
        migrations.AddField(
            model_name='d_medical',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient_Profile.Patient'),
        ),
        migrations.AddField(
            model_name='d_lab',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient_Profile.Patient'),
        ),
    ]
