# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-11 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_Profile', '0009_auto_20190110_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_result',
            name='test_type',
        ),
        migrations.AddField(
            model_name='d_lab',
            name='is_sampled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='d_lab',
            name='result',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='d_medical',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='d_medical',
            name='follow_on_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 11, 9, 25, 49, 307886, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='test_date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 1, 11, 9, 25, 49, 307886, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 11, 9, 25, 49, 307886, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='test_result',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2019, 1, 11, 9, 25, 49, 307886, tzinfo=utc)),
        ),
    ]
