# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-12 23:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_Profile', '0010_auto_20190111_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_medical',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 1, 12, 23, 49, 25, 250619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_medical',
            name='follow_on_date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 12, 23, 49, 25, 250619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='test_date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 1, 12, 23, 49, 25, 266245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 12, 23, 49, 25, 235002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='test_result',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2019, 1, 12, 23, 49, 25, 250619, tzinfo=utc)),
        ),
    ]
