# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-16 08:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_Profile', '0019_auto_20190116_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_lab',
            name='date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 16, 8, 10, 47, 933017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_lab',
            name='result',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='d_medical',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 16, 8, 10, 47, 933017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_medical',
            name='follow_on_date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 16, 8, 10, 47, 933017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='test_date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 1, 16, 8, 10, 47, 933017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 16, 8, 10, 47, 933017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='test_result',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2019, 1, 16, 8, 10, 47, 933017, tzinfo=utc)),
        ),
    ]
