# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-16 13:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_Profile', '0022_auto_20190116_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_lab',
            name='amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='d_lab',
            name='comment',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='d_lab',
            name='date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 16, 13, 16, 28, 156172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_lab',
            name='test_list',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='d_medical',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 1, 16, 13, 16, 28, 156172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='d_medical',
            name='follow_on_date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 16, 13, 16, 28, 156172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='test_date',
            field=models.DateField(verbose_name=datetime.datetime(2019, 1, 16, 13, 16, 28, 171803, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 16, 13, 16, 28, 156172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='test_result',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2019, 1, 16, 13, 16, 28, 156172, tzinfo=utc)),
        ),
    ]
