# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-08 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20190108_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='join_date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 8, 7, 42, 5, 772101, tzinfo=utc)),
        ),
    ]
