# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-20 09:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0035_auto_20190120_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='join_date',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2019, 1, 20, 9, 2, 56, 875536, tzinfo=utc)),
        ),
    ]
